name: smart_day_dart_flutter_vol_1
description: "Code samples"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  characters: ^1.3.0
  intl: ^0.20.1

  # locale_emoji: ^1.0.0
  locale_emoji:
    hosted: https://onepub.dev/api/javppsdavu/
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
